"""Add additional_info to species

Revision ID: 0c32b6f6c178
Revises: cad508684fea
Create Date: 2024-12-29 02:04:08.065490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c32b6f6c178'
down_revision: Union[str, None] = 'cad508684fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('placements', 'species_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('placements', 'enclosure_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('placements_temp_species_id_fkey', 'placements', type_='foreignkey')
    op.drop_constraint('placements_temp_enclosure_id_fkey', 'placements', type_='foreignkey')
    op.create_foreign_key(None, 'placements', 'species', ['species_id'], ['id'])
    op.create_foreign_key(None, 'placements', 'enclosures', ['enclosure_id'], ['id'])
    op.add_column('species', sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_species_additional_info', 'species', ['additional_info'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_species_additional_info', table_name='species', postgresql_using='gin')
    op.drop_column('species', 'additional_info')
    op.drop_constraint(None, 'placements', type_='foreignkey')
    op.drop_constraint(None, 'placements', type_='foreignkey')
    op.create_foreign_key('placements_temp_enclosure_id_fkey', 'placements', 'enclosures', ['enclosure_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('placements_temp_species_id_fkey', 'placements', 'species', ['species_id'], ['id'], ondelete='CASCADE')
    op.alter_column('placements', 'enclosure_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('placements', 'species_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
