"""Add enclosures and placements

Revision ID: 40564dcff3e2
Revises: d7a46af2c546
Create Date: 2024-12-28 21:44:09.918626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40564dcff3e2'
down_revision: Union[str, None] = 'd7a46af2c546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
