"""Zoo schema

Revision ID: d7a46af2c546
Revises: 
Create Date: 2024-12-28 21:02:54.254259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a46af2c546'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_indoor', sa.Boolean(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('has_water_source', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enclosures_id'), 'enclosures', ['id'], unique=False)
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('habitat', sa.String(), nullable=False),
    sa.Column('lifespan', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_id'), 'species', ['id'], unique=False)
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('enclosure_id', sa.Integer(), nullable=False),
    sa.Column('animal_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enclosure_id'], ['enclosures.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placements_id'), 'placements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placements_id'), table_name='placements')
    op.drop_table('placements')
    op.drop_index(op.f('ix_species_id'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_enclosures_id'), table_name='enclosures')
    op.drop_table('enclosures')
    # ### end Alembic commands ###
